platform: add Radxa ROCK 5A platform support
eclipse-mraa/mraa pull request #1114
Opened 2023-09-20 10:21 UTC by nascs

2023-09-20 10:23 UTC, nascs commented
Hi @tingleby, can you please take a look at the pr? I've finished testing it.

2023-09-21 16:26 UTC, tingleby commented on api/mraa/types.h
> +    MRAA_RADXA_ROCK_5A = 28,         /**< Radxa ROCK 5 Model A */
we just merged another platform, could you update the enum with a new value?

2023-09-21 16:26 UTC, tingleby requested changes
Looks good, can you just update the enum with the next value, we merged a platform just now, sorry

2023-09-22 01:37 UTC, nascs commented on api/mraa/types.h
> +    MRAA_RADXA_ROCK_5A = 28,         /**< Radxa ROCK 5 Model A */
I just updated the values. Thank you so much for taking the time to review the pr.

2023-09-27 02:39 UTC, nascs commented
Hi @tingleby,  I've changed the value. and I've resolved the conflict, can you look at it again?

2023-09-27 02:41 UTC, merged